import { useMemo } from "react";
import type { BomIngredient } from "../api/bom.types";
import { DocHeading } from "./DocHeading";
import type { FlowContent, FlowUnit } from "./PaginatedBody";

/**
 * "2.0 Master Formulation Sheet (Bill of Materials)" — the 2.1 Total Material Requirement
 * table, laid out exactly as the printed BMR (reference pages 5–6) in strict
 * black-and-white:
 *
 *   Sr. No. · Material Code · Ingredients · Spec. · Label Claim mg./Tab · Qty. Required · U O M
 *
 * `bomContent` is the single source of truth: it emits the section headings, one flow
 * unit per printed row, and the footnotes, plus the repeatable table skeleton — so the
 * paginator can break the table across real A4 pages while the column header repeats. The
 * `BomPageBody` component renders those same units on one continuous sheet.
 *
 * The row sequence is generated by walking the ingredients in order — the same order the
 * docx renderer emits — so the two never diverge:
 *   • a Layer super-header when the layer changes (bi-layer tablets)
 *   • a Part sub-header when the part changes
 *   • a blank duplicate row under every API and every $/#-compensated diluent
 *   • the coating overage folded into "Qty. Required" (e.g. 15 → 17.2500)
 *   • "Average weight of …" subtotal rows
 */

const HEADERS = [
  "Sr. No.",
  "Material Code",
  "Ingredients",
  "Spec.",
  "Label Claim mg./ Tab",
  "Qty. Required",
  "U O M",
];

function BomColgroup() {
  return (
    <colgroup>
      <col style={{ width: "7%" }} />
      <col style={{ width: "13%" }} />
      <col style={{ width: "34%" }} />
      <col style={{ width: "11%" }} />
      <col style={{ width: "13%" }} />
      <col style={{ width: "13%" }} />
      <col style={{ width: "9%" }} />
    </colgroup>
  );
}

function BomHeadRow() {
  return (
    <tr>
      {HEADERS.map((h) => (
        <th key={h} className="border border-black px-1 py-[3px] text-center align-top font-bold">
          {h}
        </th>
      ))}
    </tr>
  );
}

function BomNotes({ notes }: { notes: string[] }) {
  return (
    <div className="mt-1.5 space-y-0.5 text-[6.5pt] leading-snug">
      {notes.map((note) => (
        <p key={note}>{note}</p>
      ))}
    </div>
  );
}

/** The BOM section as paginatable flow content: headings, one unit per printed row, and
 *  the footnotes, plus the repeatable 7-column table skeleton. */
export function bomContent(
  ingredients: BomIngredient[],
  notes: string[] | undefined,
  onAddCorrection?: (row: BomIngredient, index: number) => void,
): FlowContent {
  const rows = buildRows(ingredients);

  const units: FlowUnit[] = [
    {
      type: "atom",
      key: "bom-h-2.0",
      keep: true,
      // Start the BOM on a fresh sheet (reference page 5, after the signature log). Harmless
      // on the standalone Cover+BOM preview where this is the flow's first unit.
      breakBefore: true,
      node: (
        <DocHeading level={1} number="2.0">
          Master Formulation Sheet (Bill of Materials)
        </DocHeading>
      ),
    },
    {
      type: "atom",
      key: "bom-h-2.1",
      keep: true,
      node: (
        <DocHeading level={2} number="2.1">
          Total Material Requirement
        </DocHeading>
      ),
    },
  ];

  rows.forEach((row, i) => {
    units.push({
      type: "row",
      key: `bom-row-${i}`,
      table: "bom",
      // A Layer/Part header is kept with the rows it introduces — never stranded alone.
      keep: row.kind === "band",
      node: <BomRow row={row} onAddCorrection={onAddCorrection} />,
    });
  });

  if (notes && notes.length > 0) {
    units.push({ type: "atom", key: "bom-notes", node: <BomNotes notes={notes} /> });
  }

  return {
    units,
    tables: { bom: { colgroup: <BomColgroup />, thead: <BomHeadRow /> } },
  };
}

interface BomPageBodyProps {
  ingredients: BomIngredient[];
  /** MFC footnotes (@, $, #, ##) printed under the table. */
  notes?: string[];
  onAddCorrection?: (row: BomIngredient, index: number) => void;
}

/** The 2.1 table on one continuous sheet (unpaginated) — same rows as `bomContent`. */
export function BomPageBody({ ingredients, notes, onAddCorrection }: BomPageBodyProps) {
  const rows = useMemo(() => buildRows(ingredients), [ingredients]);

  return (
    <div className="flex h-full flex-col text-[7.5pt] leading-tight text-black">
      <DocHeading level={1} number="2.0">
        Master Formulation Sheet (Bill of Materials)
      </DocHeading>
      <DocHeading level={2} number="2.1">
        Total Material Requirement
      </DocHeading>

      <table className="w-full table-fixed border-collapse">
        <BomColgroup />
        <thead>
          <BomHeadRow />
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <BomRow key={i} row={row} onAddCorrection={onAddCorrection} />
          ))}
        </tbody>
      </table>

      {notes && notes.length > 0 ? <BomNotes notes={notes} /> : null}
    </div>
  );
}

/** One rendered row of the 2.1 table. */
type Row =
  | { kind: "band"; label: string }
  | { kind: "ingredient"; ing: BomIngredient; index: number }
  | { kind: "blank"; ing: BomIngredient }
  | { kind: "avg"; ing: BomIngredient };

/**
 * Walk the ingredients and emit the printed row sequence. `curLayer`/`curPart` are
 * updated only by real ingredient rows so a subtotal ("Avg. wt.") never triggers a
 * spurious header. A layer header is emitted only for a non-empty layer (a single-layer
 * tablet has layer = "").
 */
function buildRows(ingredients: BomIngredient[]): Row[] {
  const out: Row[] = [];
  let curLayer: string | null = null;
  let curPart: string | null = null;

  ingredients.forEach((ing, index) => {
    if (ing.is_avg_weight) {
      out.push({ kind: "avg", ing });
      return;
    }

    const layer = ing.layer ?? "";
    const part = ing.part ?? "";

    if (layer !== curLayer) {
      curLayer = layer;
      curPart = null;
      if (layer) out.push({ kind: "band", label: layer });
    }
    if (part !== curPart) {
      curPart = part;
      if (part) out.push({ kind: "band", label: part });
    }

    out.push({ kind: "ingredient", ing, index });

    // The MFC repeats the API row (for the potency A.R. breakdown) and every
    // marker-compensated diluent row (for the excipient adjustment) as a blank line.
    if (ing.is_api || ing.is_compensated) {
      out.push({ kind: "blank", ing });
    }
  });

  return out;
}

function BomRow({
  row,
  onAddCorrection,
}: {
  row: Row;
  onAddCorrection?: (row: BomIngredient, index: number) => void;
}) {
  const cell = "border border-black px-1 py-[3px] align-top";

  if (row.kind === "band") {
    return (
      <tr>
        <td colSpan={7} className={`${cell} text-center font-bold`}>
          {row.label}
        </td>
      </tr>
    );
  }

  if (row.kind === "avg") {
    const { ing } = row;
    return (
      <tr>
        <td colSpan={4} className={`${cell} text-center font-bold`}>
          {ing.name.replace(/^Avg\. wt\. of /i, "Average weight of ")}
        </td>
        <td className={`${cell} text-right font-bold tabular-nums`}>
          {fmt(ing.label_claim_mg_per_unit, 3)}
        </td>
        <td className={`${cell} text-right font-bold tabular-nums`}>
          {fmt(ing.qty_required_production ?? ing.qty_per_mfc_batch, 3)}
        </td>
        <td className={`${cell} text-center font-bold`}>{ing.uom ?? ""}</td>
      </tr>
    );
  }

  if (row.kind === "blank") {
    const { ing } = row;
    return (
      <tr>
        <td className={cell}>&nbsp;</td>
        <td className={`${cell} tabular-nums`}>{ing.material_code ?? ""}</td>
        <td className={cell}>{ing.name}</td>
        <td className={cell}>{ing.specification ?? ""}</td>
        <td className={cell}>&nbsp;</td>
        <td className={cell}>&nbsp;</td>
        <td className={`${cell} text-center`}>{ing.uom ?? ""}</td>
      </tr>
    );
  }

  const { ing, index } = row;
  const clickable = Boolean(onAddCorrection);
  return (
    <tr
      className={clickable ? "cursor-pointer hover:bg-black/[0.06]" : undefined}
      onClick={onAddCorrection ? () => onAddCorrection(ing, index) : undefined}
    >
      <td className={`${cell} text-center tabular-nums`}>{ing.sr_no ?? ""}</td>
      <td className={`${cell} tabular-nums`}>{ing.material_code ?? "—"}</td>
      <td className={cell}>{ing.name}</td>
      <td className={cell}>{ing.specification ?? "—"}</td>
      <td className={`${cell} text-right tabular-nums`}>{fmt(ing.label_claim_mg_per_unit, 3)}</td>
      <td className={`${cell} text-right tabular-nums`}>{fmt(displayQty(ing), 4)}</td>
      <td className={`${cell} text-center`}>{ing.uom ?? "—"}</td>
    </tr>
  );
}

/** "Qty. Required" as printed: the scaled production quantity with any coating overage folded in. */
function displayQty(ing: BomIngredient): number | null {
  const base = ing.qty_required_production ?? ing.qty_per_mfc_batch;
  if (base === null || base === undefined) return null;
  return base * (1 + (ing.overage_pct ?? 0) / 100);
}

function fmt(value: number | null | undefined, digits: number): string {
  if (value === null || value === undefined) return "";
  return value.toFixed(digits);
}
